### PR TITLE
Fix deprecation warnings

### LINKED ISSUE #4: Need to use `__xonsh__.completers` instead of deprecated `__xonsh_completers__`
How to reproduce: start xonsh >0.8 with vox_tabcomplete.xsh activated and this warning appears:

````
/usr/local/Cellar/xonsh/0.8.3/libexec/lib/python3.7/site-packages/xontrib/vox_tabcomplete.xsh:30: DeprecationWarning: __xonsh_completers__ has been deprecated, please use __xonsh__.completers instead.
  __xonsh_completers__['vox'] = _vox_completer
`````

### PR DESCRIPTION
**Pull request by laloch**
See xonsh/xonsh#2713
Edit: closes #4.

### CODE REVIEW

**Comment by Achimh3011** [comment]
Ah, there is already a PR for #4. Please merge.

**Comment by amitkot** [comment]
Upgrading to Xonsh 0.8.3 I now also get the deprecation warning that this PR fixes.
@Granitosaurus  are you still maintaining this repo?

**Comment by BYK** [comment]
Anything we can do to get this moving @laloch?

**Comment by Achimh3011** [comment]
Short of forking this project on pypi, one can install directly from git:

````
xpip uninstall -y xonsh-vox-tabcomplete
xpip install git+https://github.com/laloch/xonsh-vox-tabcomplete.git@proxy-warnings#egg=xonsh-vox-tabcomplete
````

**Pull request merged**
